version: '3'
services:
  nifi:
    image: apache/nifi
    container_name: nifi

    ports:
      - 8333:8333
      - 10000:10000

    environment:
      NIFI_WEB_HTTP_PORT: 8333
      NIFI_HOME: /opt/nifi/nifi-current
      NIFI_LOG_DIR: /opt/nifi/nifi-current/logs
      NIFI_TOOLKIT_HOME: /opt/nifi/nifi-toolkit-current
      NIFI_PID_DIR: /opt/nifi/nifi-current/run
      NIFI_BASE_DIR: /opt/nifi

    volumes:
      - ./nifi/state:/opt/nifi/nifi-current/state
      - ./nifi/db:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/content:/opt/nifi/nifi-current/content_repository
      - ./nifi/provenance:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./nifi/conf:/opt/nifi/nifi-current/conf
    restart: on-failure